//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFletesAcarreoB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOS
    {
        public int Id_Autos { get; set; }
        public string Num_Placas { get; set; }
        public string Marca { get; set; }
        public string Kilometraje { get; set; }
        public string Cap_A { get; set; }
        public string Disponible { get; set; }
    }
}
