//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFletesAcarreoB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOFER
    {
        public int Id_Chofer { get; set; }
        public string lICENCIA_C { get; set; }
        public string N_Chofer { get; set; }
        public string ApellidoP_C { get; set; }
        public string ApellidoM_C { get; set; }
        public string Sexo { get; set; }
        public string Edad { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public System.DateTime F_Nac { get; set; }
        public string Direccion { get; set; }
        public string Disponible { get; set; }
    }
}
