//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFletesAcarreoB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int Boleta_no { get; set; }
        public int Num_Factura { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Materiales { get; set; }
        public string Total_metros { get; set; }
        public double Total_viajes { get; set; }
        public double Total_Kilometros { get; set; }
        public double Subtotal { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public string Fact_material { get; set; }
        public string Fact_licencia { get; set; }
        public string Fact_placas { get; set; }
        public string Fact_Kilometro { get; set; }
    }
}
