//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFletesAcarreoB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int Boleta_no { get; set; }
        public Nullable<int> Maquina { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Materiales { get; set; }
        public Nullable<int> Total_metros { get; set; }
        public Nullable<int> Total_viajes { get; set; }
        public Nullable<int> PP_Metro { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Fact_material { get; set; }
        public Nullable<int> Fact_licencia { get; set; }
        public string Fact_placas { get; set; }
        public Nullable<int> Fact_Kilometro { get; set; }
    
        public virtual AUTOS AUTOS { get; set; }
        public virtual CHOFER CHOFER { get; set; }
        public virtual KILOMETRO KILOMETRO { get; set; }
        public virtual MATERIALES MATERIALES1 { get; set; }
    }
}
