//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFletesAcarreoB.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISTEMAFLETESACARREOSEntities : DbContext
    {
        public SISTEMAFLETESACARREOSEntities()
            : base("name=SISTEMAFLETESACARREOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOS> AUTOS { get; set; }
        public virtual DbSet<CHOFER> CHOFER { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<KILOMETRO> KILOMETRO { get; set; }
        public virtual DbSet<MATERIALES> MATERIALES { get; set; }
    }
}
